//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFamilia
    {
        public int IdDetalleFamilia { get; set; }
        public int IdMiembro { get; set; }
        public int IdPariente { get; set; }
        public int IdParentesco { get; set; }
    
        public virtual Miembros Miembros { get; set; }
        public virtual Miembros Miembros1 { get; set; }
        public virtual Parentescos Parentescos { get; set; }
    }
}
