//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finanzas
    {
        public int IdFinanza { get; set; }
        public int IdMiembro { get; set; }
        public int IdTipoReunion { get; set; }
        public int IdTipoOfrenda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Miembros Miembros { get; set; }
        public virtual TipoOfrenda TipoOfrenda { get; set; }
        public virtual TipoReunion TipoReunion { get; set; }
    }
}
