//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampDios.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int id_usuario { get; set; }
        public string UsuarioNombre { get; set; }
        public string NombreCompleto { get; set; }
        public string password { get; set; }
        public string confirmpassword { get; set; }
        public Nullable<int> IdMiembro { get; set; }
    }
}
